version: "3.7"

services:
    client:
        build: ./client/web/app/
        restart: always
        volumes: 
            - ./client/web/app:/app:z
        command: yarn serve
        depends_on: 
            - api
    api:
        build: 
            context: ./server/api/
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./server/api:/code:z
        command: bash main.sh
        environment: 
            DB_NAME: clinica
            DB_USER: centroavancado
            DB_PASSWORD: abda143501.com
            DB_HOST: db
            DB_PORT: 5432
            SECRET_KEY: x*3y-^8_iiud0&9cx+#%t4)!+)w$rwn%_x@9m)dq9@8988(u0n
        depends_on: 
            - db
            - proxy
            
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_DB: clinica
            POSTGRES_USER: centroavancado
            POSTGRES_PASSWORD: abda143501.com

    proxy:
        image: nginx
        restart: always
        volumes: 
            - ./server/proxy/nginx/conf.d:/etc/nginx/conf.d:z
            - ./server/proxy/nginx/logs:/etc/nginx/logs:z
        ports:
            - 80:80
            - 443:443
        # command: [nginx-debug, '-g', 'daemon off;']
        environment:
            NGINX_PORT: 80
            API_HOST: api:5804
            CLIENT_HOST: client:8080

