# Generated by Django 3.0.2 on 2020-01-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200130_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Referência')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('registration', models.DateTimeField(auto_now=True, verbose_name='Data do cadasto')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de barras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Category'),
            preserve_default=False,
        ),
    ]
