# Generated by Django 3.0.2 on 2020-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200130_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ideal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum',
        ),
        migrations.AddField(
            model_name='category',
            name='ideal',
            field=models.IntegerField(verbose_name='Quantidade ideal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='minimum',
            field=models.IntegerField(verbose_name='Quantidade mínima'),
            preserve_default=False,
        ),
    ]
