# Generated by Django 3.0.2 on 2020-01-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200130_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ideal',
        ),
    ]
