# Generated by Django 3.0.2 on 2020-01-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0008_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField(auto_now=True, verbose_name='Data da requisição')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('delivered', models.DateTimeField(blank=True, null=True, verbose_name='Data da entrega')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
