# Generated by Django 3.0.2 on 2020-01-31 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='stock.Category'),
        ),
    ]
