# Generated by Django 3.0.2 on 2020-01-31 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0010_auto_20200131_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'USER'), ('dentist', 'DENTIST'), ('chamber', 'CHAMBER')], max_length=100, verbose_name='Tipo de consumidor')),
                ('dentist', models.CharField(max_length=100, verbose_name='Dentista')),
                ('chamber', models.CharField(max_length=100, verbose_name='Consultório')),
                ('other', models.CharField(max_length=100, verbose_name='Outro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
