# Generated by Django 3.0.2 on 2020-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='stock.Consumer'),
            preserve_default=False,
        ),
    ]
