# Generated by Django 3.0.2 on 2020-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_request_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('user', 'USER'), ('dentist', 'DENTIST'), ('chamber', 'CHAMBER'), ('other', 'OTHER')], max_length=100, verbose_name='Tipo de consumidor'),
        ),
    ]
