# Generated by Django 3.0.2 on 2020-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20200131_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='patient',
            field=models.CharField(max_length=100, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('USER', 'Usuário'), ('DENTIST', 'Dentista'), ('CHAMBER', 'Consultório'), ('OTHER', 'Outro'), ('PATIENT', 'Paciente')], max_length=100, verbose_name='Tipo de consumidor'),
        ),
    ]
