# Generated by Django 3.0.2 on 2020-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20200131_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('USER', 'Usuário'), ('DENTIST', 'Dentista'), ('CHAMBER', 'Consultório'), ('PATIENT', 'Paciente'), ('OTHER', 'Outro')], max_length=100, verbose_name='Tipo de consumidor'),
        ),
    ]
