# Generated by Django 3.0.2 on 2020-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20200131_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.CharField(choices=[('user', 'Usuário'), ('dentist', 'Dentista'), ('chamber', 'Consultório'), ('patient', 'Paciente'), ('other', 'Outro')], max_length=100, verbose_name='Tipo de consumidor'),
        ),
    ]
