# Generated by Django 3.0.2 on 2020-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(max_length=300, verbose_name='Observação'),
        ),
    ]
