# Generated by Django 3.0.2 on 2020-01-31 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0020_auto_20200131_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='delivered',
        ),
        migrations.AddField(
            model_name='removal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='removals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField(auto_now=True, verbose_name='Data da requisição')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveries', to='stock.Product')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='stock.Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
