# Generated by Django 3.0.2 on 2020-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20200131_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='amount',
            field=models.IntegerField(verbose_name='Retiradas'),
            preserve_default=False,
        ),
    ]
