# Generated by Django 3.0.2 on 2020-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_delivery_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='registration',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da entrega'),
        ),
    ]
