# Generated by Django 3.0.2 on 2020-01-31 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0024_auto_20200131_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField(auto_now=True, verbose_name='Data do compra')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='stock.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField(auto_now=True, verbose_name='Data do cadasto')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='additions', to='stock.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='additions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
