# Generated by Django 3.0.2 on 2020-01-31 18:51

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_addition_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Retiradas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='removal',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Retiradas'),
        ),
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.IntegerField(validators=[stock.models.validator_amount], verbose_name='Quantidade'),
        ),
    ]
