# Generated by Django 3.0.3 on 2020-03-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_auto_20200220_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='other',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumer',
            field=models.CharField(max_length=200, verbose_name='Consumidor'),
            preserve_default=False,
        ),
    ]
