# Generated by Django 3.0.6 on 2020-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_auto_20200310_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrequest',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação'),
        ),
    ]
