# Generated by Django 3.0.6 on 2020-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20200603_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrequest',
            name='consumer_type',
            field=models.CharField(choices=[('user', 'Usuário'), ('dentist', 'Dentista'), ('chamber', 'Consultório'), ('patient', 'Paciente'), ('other', 'Outro')], max_length=100, verbose_name='Tipo de consumidor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumptionrequest',
            name='consumer',
            field=models.CharField(max_length=200, verbose_name='Consumidor'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
