# Generated by Django 3.0.6 on 2020-06-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_auto_20200605_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='removal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='stock.Removal'),
            preserve_default=False,
        ),
    ]
